import './globals.css';

import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';

import Header from '@/components/core/header';
import Sidebar from '@/components/core/sidebar';
import { ThemeProvider } from '@/components/theme-provider';
import { cn } from '@/lib/utils';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
      >
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased w-full bg-muted/40"',
            fontSans.variable,
          )}
        >
          <Sidebar />
          <div className="flex flex-1 flex-col">
            <Header />
            <main className="flex-1 pl-20 pt-4">{children}</main>
          </div>
        </body>
      </ThemeProvider>
    </html>
  );
}
